/**
 * THERMOSHELTER — Passive Strategy mapper (D4-B WP3)
 * ==================================================
 * Typed frontend model for the backend's authoritative PassiveStrategy
 * contract (backend/climate/schemas.py:314, generated by
 * ClimateStrategyEngine.generate_strategy for all 6 climate zones).
 *
 * Engineering discipline:
 *  - Pure functions only; nothing here mutates ShelterDesign or any input.
 *  - Malformed/missing fields map to null / [] — never to invented defaults
 *    that would imply an engineering decision the backend did not make.
 *  - climate_mode is restricted to the backend's 6 canonical zones; an
 *    unknown value maps to null rather than being displayed as fact.
 *  - The strategy is a READ-ONLY recommendation. Nothing in this module
 *    writes to design state; comparison pairs are display data only.
 */

import { ShelterDesign } from '../types';

/** Raw backend PassiveStrategy DTO (backend/climate/schemas.py). */
export interface PassiveStrategyDto {
  version?: string;
  climate_mode?: string;
  primary_strategy?: string;
  secondary_strategies?: string[];
  solar_capture?: string;
  thermal_mass?: string;
  insulation_priority?: string;
  ventilation_strategy?: string;
  shading_strategy?: string;
  opening_strategy?: string;
  airlock?: boolean;
  thermal_buffer?: boolean;
  explanation?: string;
  rules_triggered?: string[];
  [key: string]: unknown;
}

/** Canonical climate zones — must mirror backend ClimateZone exactly. */
export const CLIMATE_MODES = [
  'EXTREME COLD',
  'COLD',
  'HOT DRY',
  'HOT HUMID',
  'TEMPERATE',
  'VARIABLE',
] as const;

export type ClimateMode = (typeof CLIMATE_MODES)[number];

/** Canonical priority levels — must mirror backend PriorityLevel exactly. */
export const PRIORITY_LEVELS = ['HIGH', 'MODERATE', 'LOW', 'MINIMIZED'] as const;

export type PriorityLevel = (typeof PRIORITY_LEVELS)[number];

/** Typed, honest frontend model of the backend strategy. */
export interface PassiveStrategyModel {
  version: string | null;
  climateMode: ClimateMode | null;
  primaryStrategy: string | null;
  secondaryStrategies: string[];
  solarCapture: PriorityLevel | null;
  thermalMass: PriorityLevel | null;
  insulationPriority: PriorityLevel | null;
  ventilationStrategy: string | null;
  shadingStrategy: string | null;
  openingStrategy: string | null;
  airlock: boolean | null;
  thermalBuffer: boolean | null;
  explanation: string | null;
  rulesTriggered: string[];
}

function asString(value: unknown): string | null {
  return typeof value === 'string' && value.trim() !== '' ? value : null;
}

function asStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((item): item is string => typeof item === 'string' && item.trim() !== '');
}

function asClimateMode(value: unknown): ClimateMode | null {
  return typeof value === 'string' && (CLIMATE_MODES as readonly string[]).includes(value)
    ? (value as ClimateMode)
    : null;
}

function asPriority(value: unknown): PriorityLevel | null {
  return typeof value === 'string' && (PRIORITY_LEVELS as readonly string[]).includes(value)
    ? (value as PriorityLevel)
    : null;
}

function asBoolean(value: unknown): boolean | null {
  return typeof value === 'boolean' ? value : null;
}

/**
 * Maps the raw strategy DTO onto the typed model. Returns null for a null/
 * non-object DTO — an absent strategy must stay absent, not be fabricated.
 */
export function mapStrategyDto(dto: unknown): PassiveStrategyModel | null {
  if (dto === null || dto === undefined || typeof dto !== 'object' || Array.isArray(dto)) {
    return null;
  }
  const d = dto as PassiveStrategyDto;
  return {
    version: asString(d.version),
    climateMode: asClimateMode(d.climate_mode),
    primaryStrategy: asString(d.primary_strategy),
    secondaryStrategies: asStringArray(d.secondary_strategies),
    solarCapture: asPriority(d.solar_capture),
    thermalMass: asPriority(d.thermal_mass),
    insulationPriority: asPriority(d.insulation_priority),
    ventilationStrategy: asString(d.ventilation_strategy),
    shadingStrategy: asString(d.shading_strategy),
    openingStrategy: asString(d.opening_strategy),
    airlock: asBoolean(d.airlock),
    thermalBuffer: asBoolean(d.thermal_buffer),
    explanation: asString(d.explanation),
    rulesTriggered: asStringArray(d.rules_triggered),
  };
}

/** One read-only "Climate-derived recommendation" vs "Current design selection" row. */
export interface StrategyComparisonPair {
  concept: string;
  /** What the climate strategy recommends (null when the backend omitted it). */
  recommendation: string | null;
  /** What the current canonical design state actually selects. */
  current: string;
  /** False when the concept has no corresponding design parameter — shown honestly. */
  represented: boolean;
}

/** Honest marker for concepts without a corresponding design parameter. */
export const NOT_REPRESENTED = 'Not represented in current design parameters';

function glazingLabel(glazing: ShelterDesign['windowGlazing']): string {
  if (glazing === 'single') return 'single glazing';
  if (glazing === 'triple') return 'triple glazing';
  return 'double glazing';
}

function priorityRecommendation(priority: PriorityLevel | null, intent: string): string | null {
  if (!priority) return null;
  switch (priority) {
    case 'HIGH':
      return `Prioritize ${intent} (HIGH)`;
    case 'MODERATE':
      return `Moderate ${intent} (MODERATE)`;
    case 'LOW':
      return `Low ${intent} priority (LOW)`;
    case 'MINIMIZED':
      return `Minimize ${intent} (MINIMIZED)`;
  }
}

/**
 * Builds the recommendation/current-selection pairs using ONLY real design
 * state. Concepts without a design parameter carry `represented: false` and
 * the honest NOT_REPRESENTED marker — no fabricated values.
 */
export function buildStrategyComparison(
  model: PassiveStrategyModel,
  design: ShelterDesign,
): StrategyComparisonPair[] {
  const massCurrent = design.thermalMassEnabled && design.thermalMassThickness > 0
    ? `Enabled — ${design.thermalMassThickness} cm floor-core mass`
    : 'Disabled';
  const insulationCurrent =
    design.insulationType !== 'None' && design.insulationThickness > 0
      ? `${design.insulationType} — ${design.insulationThickness} cm`
      : 'None';

  return [
    {
      concept: 'Thermal mass',
      recommendation: priorityRecommendation(model.thermalMass, 'thermal mass storage'),
      current: massCurrent,
      represented: true,
    },
    {
      concept: 'Envelope insulation',
      recommendation: priorityRecommendation(model.insulationPriority, 'envelope insulation'),
      current: insulationCurrent,
      represented: true,
    },
    {
      concept: 'Solar capture',
      recommendation: priorityRecommendation(model.solarCapture, 'solar heat capture'),
      current: `Orientation ${design.orientation}° · ${glazingLabel(design.windowGlazing)} · ${design.windowArea} m² glazing`,
      represented: true,
    },
    {
      concept: 'Ventilation',
      recommendation: model.ventilationStrategy,
      current: `${design.ach} air changes per hour`,
      represented: true,
    },
    {
      concept: 'Fenestration / openings',
      recommendation: model.openingStrategy,
      current: `${design.windowArea} m² windows · ${design.doorArea} m² door`,
      represented: true,
    },
    {
      concept: 'Solar shading',
      recommendation: model.shadingStrategy,
      current: NOT_REPRESENTED,
      represented: false,
    },
    {
      concept: 'Entrance airlock',
      recommendation: model.airlock === null ? null : model.airlock ? 'Required' : 'Not required',
      current: NOT_REPRESENTED,
      represented: false,
    },
    {
      concept: 'Thermal buffer zones',
      recommendation:
        model.thermalBuffer === null ? null : model.thermalBuffer ? 'Recommended' : 'Not required',
      current: NOT_REPRESENTED,
      represented: false,
    },
  ];
}
